#ifndef __SCT_FSM_H__
#define __SCT_FSM_H__

/* Generated by fzmparser version 2.5 --- DO NOT EDIT! */

#include "sct_user.h"

extern void sct_fsm_init (void);

/* macros for defining the mapping between IRQ and events */
#define sct_fsm_IRQ_EVENT_SCT_IRQ (0)

/* Output assignments (and their defaults if specified) */
#define sct_fsm_OUTPUT_Output_pin_0 (0)

#define sct_fsm_setOutputDefault() do {LPC_SCT->OUTPUT = (LPC_SCT->OUTPUT & ~0x00000000) | 0x00000000;} while(0)


/* Match register reload macro definitions */
#define sct_fsm_reload_MATCH0(value) do {LPC_SCT->MATCHREL_L[0] = value;} while(0)
#define sct_fsm_reload_MATCH1(value) do {LPC_SCT->MATCHREL_L[1] = value;} while(0)
#define sct_fsm_reload_MATCH2(value) do {LPC_SCT->MATCHREL_L[2] = value;} while(0)
#define sct_fsm_reload_MATCH3(value) do {LPC_SCT->MATCHREL_L[3] = value;} while(0)
#define sct_fsm_reload_MATCH4(value) do {LPC_SCT->MATCHREL_H[0] = value;} while(0)

#endif
