
/* Generated by fzmparser version 2.5 --- DO NOT EDIT! */

/* Uses following resources: */
/* 5 events, 1+1 states, 0 inputs, 1 outputs, 4+1 match regs, 0+0 capture regs */

#include "sct_fsm.h"


void sct_fsm_init (void)
{
LPC_SCT->CONFIG = (LPC_SCT->CONFIG & ~0x00060001) | 0x00000000; /* SPLIT */

/* MATCH/CAPTURE registers */
LPC_SCT->REGMODE_L = 0x0000;         /* L: 4x MATCH, 0x CAPTURE, 1 unused */
LPC_SCT->REGMODE_H = 0x0000;             /* H: 1x MATCH, 0x CAPTURE, 4 unused */
LPC_SCT->MATCH_L[0] = irqtiming;             /* MATCH0 */
LPC_SCT->MATCHREL_L[0] = irqtiming;
LPC_SCT->MATCH_L[1] = up1;             /* MATCH1 */
LPC_SCT->MATCHREL_L[1] = up1;
LPC_SCT->MATCH_L[2] = down2;             /* MATCH2 */
LPC_SCT->MATCHREL_L[2] = down2;
LPC_SCT->MATCH_L[3] = up3;             /* MATCH3 */
LPC_SCT->MATCHREL_L[3] = up3;
LPC_SCT->MATCH_H[0] = maxcount;             /* MATCH4 */
LPC_SCT->MATCHREL_H[0] = maxcount;

/* OUTPUT registers */
LPC_SCT->OUT[0].SET = 0x00000006;        /* Output_pin_0 */
LPC_SCT->OUT[0].CLR = 0x00000018;
  /* Unused outputs must not be affected by any event */
LPC_SCT->OUT[1].SET = 0;
LPC_SCT->OUT[1].CLR = 0;
LPC_SCT->OUT[2].SET = 0;
LPC_SCT->OUT[2].CLR = 0;
LPC_SCT->OUT[3].SET = 0;
LPC_SCT->OUT[3].CLR = 0;

/* Conflict resolution register */

/* EVENT registers */
LPC_SCT->EVENT[0].CTRL = 0x00005000;     /* L: --> state L_ENTRY */
LPC_SCT->EVENT[0].STATE = 0x00000001;
LPC_SCT->EVENT[1].CTRL = 0x00005003;     /* L: --> state L_ENTRY */
LPC_SCT->EVENT[1].STATE = 0x00000001;
LPC_SCT->EVENT[2].CTRL = 0x00005001;     /* L: --> state L_ENTRY */
LPC_SCT->EVENT[2].STATE = 0x00000001;
LPC_SCT->EVENT[3].CTRL = 0x00005002;     /* L: --> state L_ENTRY */
LPC_SCT->EVENT[3].STATE = 0x00000001;
LPC_SCT->EVENT[4].CTRL = 0x00005010;     /* H: --> state H_ENTRY */
LPC_SCT->EVENT[4].STATE = 0x00000001;
  /* Unused events must not have any effect */
LPC_SCT->EVENT[5].STATE = 0;

/* STATE registers */
LPC_SCT->STATE_L = 0;
LPC_SCT->STATE_H = 0;

/* state names assignment: */
  /* State L 0: L_ENTRY */
  /* State H 0: H_ENTRY */

/* CORE registers */
LPC_SCT->START_L = 0x0010;
LPC_SCT->STOP_L =  0x0001;
LPC_SCT->HALT_L =  0x0000;
LPC_SCT->LIMIT_L = 0x0001;
LPC_SCT->START_H = 0x0000;
LPC_SCT->STOP_H =  0x0000;
LPC_SCT->HALT_H =  0x0000;
LPC_SCT->LIMIT_H = 0x0010;
LPC_SCT->EVEN =    0x00000001;

}
